### ISSUE TITLE
代码优化

### ISSUE THREAD

**Issue by wsmeichao** [eJayYoung/simple-react-reflux#1]
components/TodoSummary/TodoSummary.jsx 里面的onCheckAll函数其实可以进行优化
`  me.data.allChecked = !me.data.allChecked;
    me.data.itemList.map(n => {
      if(me.data.allChecked) {
        n.isDone = true;
      }else{
        n.isDone = false;
      }
    })`
优化成：
`me.data.allChecked = !me.data.allChecked;
me.data.itemList.map(n => {
      n.isDone =  me.data.allChecked;
    })`

**Comment by eJayYoung** [comment]
Thanks，已更新，看的好仔细

**Comment by wsmeichao** [comment]
me.data.allChecked = !me.data.allChecked; me.data.itemList.map(n => { n.isDone = me.data.allChecked; })   不好意思，刚刚打错了，应该是这样的

**Comment by eJayYoung** [comment]
。。。不好意思，现在在忙，也还没校验，晚点改，谢谢提ISUEE

**Comment by eJayYoung** [comment]
已修改完，并校验过了，并在onClearAllDone里面清空了allChecked的选中状态，十分感谢您的支持，是对我最大的鼓励！
